name: CI Pipeline with Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

  deploy:
    needs: build   # will run only if build is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Deployment
        run: |
          echo "Starting deployment..."
          echo "Packaging app..."
          echo "Deploying app to staging server..."
          echo "Deployment successful ✅"
