name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to simulated environment
        run: |
          echo "🚀 Starting deployment..."
          mkdir -p deploy
          cp -r app deploy/
          echo "✅ Deployment successful to mock server!"
