name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Run Linter
        run: flake8 app/ test/

      - name: Run Tests
        run: pytest

      - name: Create dummy report
        run: echo "This is a test report for Day 21" > report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4

        with:

        name: test-report
        path: report.txt
